name: secret-scan-git-secrets
on: [push, pull_request]
jobs:
  git-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install git-secrets
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          git clone https://github.com/awslabs/git-secrets.git
          sudo make -C git-secrets install
      - name: Scan with git-secrets
        run: |
          git secrets --register-aws --global || true
          git secrets --scan -r .
